name: Publish Snapshot to GitHub Packages

on:
  push:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Publish package
        run: mvn --batch-mode deploy -DrepositoryId=github -Dmaven.deploy.skip=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}