name: test
on: push
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Publish package
        run: mvn --batch-mode deploy -DaltDeploymentRepository=github::default::https://github.com/extrawest/Extrawest-OCPI-2.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}